/**
 * Data Context for Softball Dashboard
 * 
 * Manages the global state for player data and team statistics.
 * Data is embedded directly in the application for permanent availability.
 */

import React, { createContext, useContext, ReactNode } from 'react';
import { Player, TeamStats } from '../types/csv';

interface DataContextType {
  // Data state
  players: Player[];
  teamStats: TeamStats;
  
  // Computed values
  topHitters: Player[];
  topPitchers: Player[];
  teamLeaders: {
    batting: Player[];
    rbis: Player[];
    stolenBases: Player[];
    wins: Player[];
    strikeouts: Player[];
  };
}

const DataContext = createContext<DataContextType | undefined>(undefined);

interface DataProviderProps {
  children: ReactNode;
}

// Embedded team data - permanently available
const EMBEDDED_PLAYERS: Player[] = [
  {
    id: "scarlett-walter",
    name: "Scarlett Walter",
    position: "IF",
    gamesPlayed: 24,
    battingAvg: 0.22,
    onBasePct: 0.289,
    sluggingPct: 0.268,
    ops: 0.557,
    hits: 9,
    doubles: 0,
    triples: 1,
    homeRuns: 0,
    rbis: 5,
    runs: 5,
    walks: 4,
    strikeouts: 7,
    stolenBases: 6,
    caughtStealing: 1,
    inningsPitched: 0,
    wins: 0,
    losses: 0,
    saves: 0,
    earnedRuns: 0,
    era: 0,
    whip: 0,
    pitchingStrikeouts: 0,
    totalChances: 6,
    assists: 1,
    putouts: 2,
    fieldingPct: 0.5,
    errors: 3,
    doublePlays: 0,
    inningsCatching: 0,
    passedBalls: 0,
    stolenBasesAllowed: 0,
    caughtStealingPct: 0,
    trend: "stable"
  },
  {
    id: "emma-blake",
    name: "Emma Blake",
    position: "P",
    gamesPlayed: 26,
    battingAvg: 0.263,
    onBasePct: 0.333,
    sluggingPct: 0.298,
    ops: 0.632,
    hits: 15,
    doubles: 2,
    triples: 0,
    homeRuns: 0,
    rbis: 2,
    runs: 17,
    walks: 6,
    strikeouts: 5,
    stolenBases: 10,
    caughtStealing: 2,
    inningsPitched: 7.1,
    wins: 1,
    losses: 1,
    saves: 0,
    earnedRuns: 11,
    era: 9,
    whip: 3,
    pitchingStrikeouts: 6,
    totalChances: 69,
    assists: 38,
    putouts: 25,
    fieldingPct: 0.913,
    errors: 6,
    doublePlays: 3,
    inningsCatching: 0,
    passedBalls: 0,
    stolenBasesAllowed: 0,
    caughtStealingPct: 0,
    trend: "stable"
  },
  {
    id: "eden-blumenthal",
    name: "Eden Blumenthal",
    position: "C",
    gamesPlayed: 26,
    battingAvg: 0.475,
    onBasePct: 0.522,
    sluggingPct: 0.656,
    ops: 1.177,
    hits: 29,
    doubles: 5,
    triples: 3,
    homeRuns: 0,
    rbis: 8,
    runs: 17,
    walks: 7,
    strikeouts: 12,
    stolenBases: 13,
    caughtStealing: 1,
    inningsPitched: 0,
    wins: 0,
    losses: 0,
    saves: 0,
    earnedRuns: 0,
    era: 0,
    whip: 0,
    pitchingStrikeouts: 0,
    totalChances: 83,
    assists: 14,
    putouts: 67,
    fieldingPct: 0.976,
    errors: 2,
    doublePlays: 2,
    inningsCatching: 113.2,
    passedBalls: 11,
    stolenBasesAllowed: 42,
    caughtStealingPct: 16,
    trend: "up"
  },
  {
    id: "livia-marshall",
    name: "Livia Marshall",
    position: "IF",
    gamesPlayed: 14,
    battingAvg: 0.045,
    onBasePct: 0.125,
    sluggingPct: 0.045,
    ops: 0.17,
    hits: 1,
    doubles: 0,
    triples: 0,
    homeRuns: 0,
    rbis: 1,
    runs: 2,
    walks: 2,
    strikeouts: 7,
    stolenBases: 2,
    caughtStealing: 0,
    inningsPitched: 0,
    wins: 0,
    losses: 0,
    saves: 0,
    earnedRuns: 0,
    era: 0,
    whip: 0,
    pitchingStrikeouts: 0,
    totalChances: 3,
    assists: 1,
    putouts: 2,
    fieldingPct: 1,
    errors: 0,
    doublePlays: 0,
    inningsCatching: 0,
    passedBalls: 0,
    stolenBasesAllowed: 0,
    caughtStealingPct: 0,
    trend: "down"
  },
  {
    id: "ava-walker",
    name: "Ava Walker",
    position: "P",
    gamesPlayed: 26,
    battingAvg: 0.304,
    onBasePct: 0.361,
    sluggingPct: 0.357,
    ops: 0.718,
    hits: 17,
    doubles: 1,
    triples: 1,
    homeRuns: 0,
    rbis: 15,
    runs: 11,
    walks: 4,
    strikeouts: 8,
    stolenBases: 8,
    caughtStealing: 1,
    inningsPitched: 11.1,
    wins: 0,
    losses: 1,
    saves: 0,
    earnedRuns: 9,
    era: 4.765,
    whip: 1.588,
    pitchingStrikeouts: 5,
    totalChances: 155,
    assists: 8,
    putouts: 140,
    fieldingPct: 0.955,
    errors: 7,
    doublePlays: 5,
    inningsCatching: 0,
    passedBalls: 0,
    stolenBasesAllowed: 0,
    caughtStealingPct: 0,
    trend: "stable"
  },
  {
    id: "ayla-ale-ali",
    name: "Ayla Ale-Ali",
    position: "IF",
    gamesPlayed: 19,
    battingAvg: 0.219,
    onBasePct: 0.286,
    sluggingPct: 0.219,
    ops: 0.504,
    hits: 7,
    doubles: 0,
    triples: 0,
    homeRuns: 0,
    rbis: 4,
    runs: 3,
    walks: 3,
    strikeouts: 6,
    stolenBases: 6,
    caughtStealing: 0,
    inningsPitched: 0,
    wins: 0,
    losses: 0,
    saves: 0,
    earnedRuns: 0,
    era: 0,
    whip: 0,
    pitchingStrikeouts: 0,
    totalChances: 55,
    assists: 26,
    putouts: 25,
    fieldingPct: 0.927,
    errors: 4,
    doublePlays: 3,
    inningsCatching: 0,
    passedBalls: 0,
    stolenBasesAllowed: 0,
    caughtStealingPct: 0,
    trend: "stable"
  },
  {
    id: "cosi-quentin",
    name: "Cosi Quentin",
    position: "IF",
    gamesPlayed: 24,
    battingAvg: 0.295,
    onBasePct: 0.367,
    sluggingPct: 0.432,
    ops: 0.799,
    hits: 13,
    doubles: 2,
    triples: 2,
    homeRuns: 0,
    rbis: 11,
    runs: 11,
    walks: 3,
    strikeouts: 3,
    stolenBases: 14,
    caughtStealing: 0,
    inningsPitched: 0,
    wins: 0,
    losses: 0,
    saves: 0,
    earnedRuns: 0,
    era: 0,
    whip: 0,
    pitchingStrikeouts: 0,
    totalChances: 20,
    assists: 1,
    putouts: 12,
    fieldingPct: 0.65,
    errors: 7,
    doublePlays: 1,
    inningsCatching: 0,
    passedBalls: 0,
    stolenBasesAllowed: 0,
    caughtStealingPct: 0,
    trend: "stable"
  },
  {
    id: "sienna-duncan",
    name: "Sienna Duncan",
    position: "P",
    gamesPlayed: 25,
    battingAvg: 0.389,
    onBasePct: 0.45,
    sluggingPct: 0.407,
    ops: 0.857,
    hits: 21,
    doubles: 1,
    triples: 0,
    homeRuns: 0,
    rbis: 6,
    runs: 15,
    walks: 6,
    strikeouts: 9,
    stolenBases: 9,
    caughtStealing: 1,
    inningsPitched: 62.1,
    wins: 9,
    losses: 5,
    saves: 0,
    earnedRuns: 42,
    era: 4.043,
    whip: 1.877,
    pitchingStrikeouts: 34,
    totalChances: 57,
    assists: 36,
    putouts: 16,
    fieldingPct: 0.912,
    errors: 5,
    doublePlays: 3,
    inningsCatching: 0,
    passedBalls: 0,
    stolenBasesAllowed: 0,
    caughtStealingPct: 0,
    trend: "up"
  },
  {
    id: "ava-wund",
    name: "Ava Wund",
    position: "C",
    gamesPlayed: 26,
    battingAvg: 0.2,
    onBasePct: 0.308,
    sluggingPct: 0.2,
    ops: 0.508,
    hits: 9,
    doubles: 0,
    triples: 0,
    homeRuns: 0,
    rbis: 5,
    runs: 4,
    walks: 4,
    strikeouts: 14,
    stolenBases: 5,
    caughtStealing: 1,
    inningsPitched: 0,
    wins: 0,
    losses: 0,
    saves: 0,
    earnedRuns: 0,
    era: 0,
    whip: 0,
    pitchingStrikeouts: 0,
    totalChances: 24,
    assists: 2,
    putouts: 13,
    fieldingPct: 0.625,
    errors: 9,
    doublePlays: 0,
    inningsCatching: 2,
    passedBalls: 0,
    stolenBasesAllowed: 1,
    caughtStealingPct: 0,
    trend: "stable"
  },
  {
    id: "natalia-paratore",
    name: "Natalia Paratore",
    position: "IF",
    gamesPlayed: 23,
    battingAvg: 0.405,
    onBasePct: 0.51,
    sluggingPct: 0.452,
    ops: 0.962,
    hits: 17,
    doubles: 2,
    triples: 0,
    homeRuns: 0,
    rbis: 7,
    runs: 11,
    walks: 9,
    strikeouts: 5,
    stolenBases: 10,
    caughtStealing: 2,
    inningsPitched: 0,
    wins: 0,
    losses: 0,
    saves: 0,
    earnedRuns: 0,
    era: 0,
    whip: 0,
    pitchingStrikeouts: 0,
    totalChances: 14,
    assists: 3,
    putouts: 10,
    fieldingPct: 0.929,
    errors: 1,
    doublePlays: 1,
    inningsCatching: 0,
    passedBalls: 0,
    stolenBasesAllowed: 0,
    caughtStealingPct: 0,
    trend: "up"
  },
  {
    id: "cora-wall",
    name: "Cora Wall",
    position: "P",
    gamesPlayed: 18,
    battingAvg: 0.071,
    onBasePct: 0.212,
    sluggingPct: 0.071,
    ops: 0.284,
    hits: 2,
    doubles: 0,
    triples: 0,
    homeRuns: 0,
    rbis: 5,
    runs: 2,
    walks: 5,
    strikeouts: 7,
    stolenBases: 2,
    caughtStealing: 0,
    inningsPitched: 9,
    wins: 0,
    losses: 0,
    saves: 0,
    earnedRuns: 10,
    era: 6.667,
    whip: 2.667,
    pitchingStrikeouts: 4,
    totalChances: 28,
    assists: 17,
    putouts: 8,
    fieldingPct: 0.893,
    errors: 3,
    doublePlays: 0,
    inningsCatching: 0,
    passedBalls: 0,
    stolenBasesAllowed: 0,
    caughtStealingPct: 0,
    trend: "down"
  },
  {
    id: "ava-ale-ali",
    name: "Ava Ale-Ali",
    position: "P",
    gamesPlayed: 26,
    battingAvg: 0.423,
    onBasePct: 0.492,
    sluggingPct: 0.423,
    ops: 0.915,
    hits: 22,
    doubles: 0,
    triples: 0,
    homeRuns: 0,
    rbis: 22,
    runs: 15,
    walks: 7,
    strikeouts: 3,
    stolenBases: 8,
    caughtStealing: 0,
    inningsPitched: 25.2,
    wins: 2,
    losses: 5,
    saves: 0,
    earnedRuns: 26,
    era: 6.078,
    whip: 2.182,
    pitchingStrikeouts: 15,
    totalChances: 62,
    assists: 26,
    putouts: 27,
    fieldingPct: 0.855,
    errors: 9,
    doublePlays: 2,
    inningsCatching: 0,
    passedBalls: 0,
    stolenBasesAllowed: 0,
    caughtStealingPct: 0,
    trend: "up"
  }
];

const EMBEDDED_TEAM_STATS: TeamStats = {
  totalGames: 26,
  totalWins: 12,
  totalLosses: 12,
  teamBattingAvg: 0.303,
  teamERA: 5.084,
  totalRuns: 113,
  totalRBIs: 91,
  totalHits: 162,
  totalHomeRuns: 0,
  totalStolenBases: 93,
  totalStrikeouts: 64,
  totalErrors: 56,
  fieldingPercentage: 0.903
};

export const DataProvider: React.FC<DataProviderProps> = ({ children }) => {
  // Computed values
  const topHitters = [...EMBEDDED_PLAYERS]
    .filter(player => player.gamesPlayed >= 10)
    .sort((a, b) => b.battingAvg - a.battingAvg)
    .slice(0, 5);

  const topPitchers = [...EMBEDDED_PLAYERS]
    .filter(player => player.inningsPitched > 0)
    .sort((a, b) => (a.era || 999) - (b.era || 999))
    .slice(0, 5);

  const teamLeaders = {
    batting: [...EMBEDDED_PLAYERS]
      .filter(player => player.gamesPlayed >= 10)
      .sort((a, b) => b.battingAvg - a.battingAvg)
      .slice(0, 3),
    rbis: [...EMBEDDED_PLAYERS]
      .sort((a, b) => b.rbis - a.rbis)
      .slice(0, 3),
    stolenBases: [...EMBEDDED_PLAYERS]
      .sort((a, b) => b.stolenBases - a.stolenBases)
      .slice(0, 3),
    wins: [...EMBEDDED_PLAYERS]
      .filter(player => player.inningsPitched > 0)
      .sort((a, b) => b.wins - a.wins)
      .slice(0, 3),
    strikeouts: [...EMBEDDED_PLAYERS]
      .filter(player => player.inningsPitched > 0)
      .sort((a, b) => b.pitchingStrikeouts - a.pitchingStrikeouts)
      .slice(0, 3)
  };

  const value: DataContextType = {
    players: EMBEDDED_PLAYERS,
    teamStats: EMBEDDED_TEAM_STATS,
    topHitters,
    topPitchers,
    teamLeaders
  };

  return (
    <DataContext.Provider value={value}>
      {children}
    </DataContext.Provider>
  );
};

export const useData = (): DataContextType => {
  const context = useContext(DataContext);
  if (context === undefined) {
    throw new Error('useData must be used within a DataProvider');
  }
  return context;
}; 